print("Print in new line:")
print("Akriti\nSrivastava")
print("\n")
print("Print double quotes in between:")
print("Akriti\"Srivastava")
print("\n")
phrase = "Pursuit of Happiness"
print(phrase)
print(phrase + " is not a movie but an inspiration ")
print("Print in upper case:")
print(phrase.upper())
print(phrase.lower())
print(phrase.islower())
print(phrase.isupper())
print(len(phrase))
print(phrase[5])
